move tsc_diff() before it is used
analyze.c:270: warning: implicit declaration of function 'tsc_diff'
analyze.c:270: warning: nested extern declaration of 'tsc_diff'
[..]